---
title: "Chapter_04"
output: html_notebook
---

```{r, message=FALSE}
library(rethinking)
```


# 4.1 Why normal distributions are normal

```{r}
pos <- replicate(1000, sum(runif(16, -1, 1)))
hist(pos)
plot(density(pos))
dens(pos)
```

```{r}
# 4.2
prod(1 + runif(12, 0, 0.1))
growth <- replicate(10000, prod(1 + runif(12, 0, 0.1)))
dens(growth, norm.comp = TRUE)

big <- replicate(10000, prod(1 + runif(12, 0, 0.5)))
dens(big, norm.comp = TRUE)

small <- replicate(10000, prod(1 + runif(12, 0, 0.01)))
dens(small, norm.comp = TRUE)
```

```{r}
# 4.5
log.big <- replicate(10000, log(prod(1 + runif(12, 0, 0.5))))
dens(log.big, norm.comp = TRUE)
```


# 4.2 A language for describing models

```{r}
# 4.6
w <- 6
n <- 9
p_grid <- seq(from = 0, to = 1, length.out = 100)
posterior <- dbinom(w, n, p_grid) * dunif(p_grid, 0, 1)
posterior <- posterior/sum(posterior)

```

# 4.3 A Gaussian model of height

```{r, message=FALSE}
library(rethinking)
data("Howell1")
d <- Howell1
d
str(d)
```

```{r}
d$height
d2 <- d[d$age >= 18,]
dens(d2$height)
curve(dnorm(x, 178, 20), from = 100, to = 250)
curve(dunif(x, 0, 50), from = -10, to = 60)
```

```{r}
# 4.13
sample_mu <- rnorm(1e4, 178, 20)
sample_sigma <- runif(1e4, 0, 50)
prior_h <- rnorm(1e4, sample_mu, sample_sigma)
dens(prior_h)
```

## 4.3.3 Grid approximation of the posterior distribution

```{r}
## R code 4.14
mu.list <- seq( from=140, to=160 , length.out=200 )
sigma.list <- seq( from=4 , to=9 , length.out=200 )
post <- expand.grid( mu=mu.list , sigma=sigma.list )
post$LL <- sapply( 1:nrow(post) , function(i) sum( dnorm(
                d2$height ,
                mean=post$mu[i] ,
                sd=post$sigma[i] ,
                log=TRUE ) ) )
post$prod <- post$LL + dnorm( post$mu , 178 , 20 , TRUE ) +
    dunif( post$sigma , 0 , 50 , TRUE )
post$prob <- exp( post$prod - max(post$prod) )

```

```{r}
# 4.15
contour_xyz(post$mu, post$sigma, post$prob)
image_xyz(post$mu, post$sigma, post$prob)
```

## 4.3.4 Sampling from the posterior

```{r}
# 4.17
sample.rows <- sample(1:nrow(post), size = 1e4, replace = TRUE, prob = post$prob)
sample.mu <- post$mu[sample.rows]
sample.sigma <- post$sigma[sample.rows]

plot(sample.mu, sample.sigma, cex=1, pch = 16, col = col.alpha(rangi2, 0.1))

```

```{r}
dens(sample.mu)
dens(sample.sigma)
```

```{r 4.20}
HPDI(sample.mu)
HPDI(sample.sigma)
```

```{r 4.21}
d3 <- sample(d2$height, size = 20)
```

```{r 4.22}
mu.list <- seq( from=150, to=170 , length.out=200 )
sigma.list <- seq( from=4 , to=20 , length.out=200 )
post2 <- expand.grid( mu=mu.list , sigma=sigma.list )
post2$LL <- sapply( 1:nrow(post2) , function(i)
    sum( dnorm( d3 , mean=post2$mu[i] , sd=post2$sigma[i] ,
    log=TRUE ) ) )
post2$prod <- post2$LL + dnorm( post2$mu , 178 , 20 , TRUE ) +
    dunif( post2$sigma , 0 , 50 , TRUE )
post2$prob <- exp( post2$prod - max(post2$prod) )
sample2.rows <- sample( 1:nrow(post2) , size=1e4 , replace=TRUE ,
    prob=post2$prob )
sample2.mu <- post2$mu[ sample2.rows ]
sample2.sigma <- post2$sigma[ sample2.rows ]
plot( sample2.mu , sample2.sigma , cex=0.5 ,
    col=col.alpha(rangi2,0.1) ,
    xlab="mu" , ylab="sigma" , pch=16 )
```

```{r}
dens(sample2.sigma, norm.comp = TRUE)
```

## 4.3.5 Fitting the model with map
```{r 4.24}
library(rethinking)
data("Howell1")
d <- Howell1
d2 <- d[d$age >= 18,]
```

```{r 4.25}
flist <- alist(
  height ~ dnorm(mu, sigma),
  mu ~ dnorm(178, 20),
  sigma ~ dunif(0, 50)
)

m4.1 <- map(flist, data = d2)

precis(m4.1)
```

```{r 4.29}
m4.2 <- map(
  alist(
    height ~ dnorm(mu, sigma),
    mu ~ dnorm(178, 0.1),
    sigma ~ dunif(0, 50)
  ), 
  data = d2
)

precis(m4.2)
```

## 4.3.6 Sampling from a map fit
```{r 4.30}
vcov(m4.1)
```

```{r 4.31}
diag(vcov(m4.1))
cov2cor(vcov(m4.1))
```

```{r 4.32}
library(rethinking)
post <- extract.samples(m4.1, n = 1e4)
head(post)
precis(post)
```

```{r}
plot(post)
```

